# Generated by Django 4.0.5 on 2022-06-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('preview', models.CharField(max_length=1000, verbose_name='Описание')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='Тип MD')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ('-created_at',),
            },
        ),
    ]
