# Generated by Django 4.0.5 on 2022-06-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('name_first', models.CharField(max_length=128, verbose_name='Имя')),
                ('name_second', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('day_birth', models.DateField(verbose_name='Дата рождения')),
                ('courses', models.ManyToManyField(to='mainapp.course')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
